baseURL = "http://localhost:1313/"
title = "Your Name"
theme = "Tranquilpeak"

[params]
  sidebarBehavior = 4
  ga = { async = false }
  
  [params.author]
    name = "Your Name"
    bio = "Software Engineer. Climber. Snowboarder."
    picture = "/images/yourpic.png" # Place your image in the static/images/ folder

# Main navigation menu (sidebar)
[[menu.main]]
  weight = 1
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"

[[menu.main]]
  weight = 2
  identifier = "projects"
  name = "Projects"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-code\"></i>"
  url = "/categories/projects"

[[menu.main]]
  weight = 3
  identifier = "blog"
  name = "Blog"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-pen-square\"></i>"
  url = "/categories/blog"

[[menu.main]]
  weight = 4
  identifier = "tags"
  name = "Tags"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-tags\"></i>"
  url = "/tags"

[[menu.main]]
  weight = 5
  identifier = "about"
  name = "About"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-user\"></i>"
  url = "/about"

# Social links (sidebar)
[[menu.links]]
  weight = 1
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fab fa-lg fa-github\"></i>"
  url = "https://github.com/yourusername"

[[menu.links]]
  weight = 2
  identifier = "medium"
  name = "Medium"
  pre = "<i class=\"sidebar-button-icon fab fa-lg fa-medium\"></i>"
  url = "https://medium.com/@yourusername" 